apiVersion: v1
kind: Service
metadata:
  name: bsvd
  namespace: default
spec:
  ports:
    - port: 8333
      targetPort: 8333
  selector:
    service: bsvd
  type: LoadBalancer
  externalTrafficPolicy: Local
